// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// ReviewsColumns holds the columns for the "reviews" table.
	ReviewsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID, Unique: true},
		{Name: "created_at", Type: field.TypeUint32},
		{Name: "updated_at", Type: field.TypeUint32},
		{Name: "deleted_at", Type: field.TypeUint32},
		{Name: "app_id", Type: field.TypeUUID, Nullable: true},
		{Name: "reviewer_id", Type: field.TypeUUID, Nullable: true},
		{Name: "domain", Type: field.TypeString, Nullable: true, Default: ""},
		{Name: "object_id", Type: field.TypeUUID, Nullable: true},
		{Name: "trigger", Type: field.TypeString, Nullable: true, Default: "DefaultTriggerType"},
		{Name: "object_type", Type: field.TypeString, Nullable: true, Default: "DefaultObjectType"},
		{Name: "state", Type: field.TypeString, Nullable: true, Default: "DefaultReviewState"},
		{Name: "message", Type: field.TypeString, Nullable: true, Default: ""},
	}
	// ReviewsTable holds the schema information for the "reviews" table.
	ReviewsTable = &schema.Table{
		Name:       "reviews",
		Columns:    ReviewsColumns,
		PrimaryKey: []*schema.Column{ReviewsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		ReviewsTable,
	}
)

func init() {
}
